// Strings.cs -- ME-Tools Localisation
// Static string table for English (default), German and Romanian.
// Usage: S.Get("key") or S.L["key"]
// Call S.SetLanguage("en"/"de"/"ro") on startup and on language change.
// Mayer E-Concept SRL
using System.Collections.Generic;

namespace METools
{
    public static class S
    {
        private static string _lang = "en";

        public static void SetLanguage(string lang)
        {
            _lang = (lang == "de" || lang == "ro") ? lang : "en";
        }

        public static string Get(string key)
        {
            if (_lang == "de" && _de.TryGetValue(key, out var de)) return de;
            if (_lang == "ro" && _ro.TryGetValue(key, out var ro)) return ro;
            if (_en.TryGetValue(key, out var en)) return en;
            return key; // fallback: show the key itself
        }

        // Shorthand
        public static string _(string key) => Get(key);

        // ── English (source of truth) ─────────────────────────────────────
        private static readonly Dictionary<string, string> _en = new()
        {
            // ── General ───────────────────────────────────────────────────
            ["cancel"]          = "Cancel",
            ["save"]            = "Save",
            ["delete"]          = "Delete",
            ["close"]           = "Close",
            ["refresh"]         = "Refresh",
            ["none"]            = "None",
            ["auto"]            = "Auto",
            ["custom"]          = "Custom",
            ["preview"]         = "Preview",
            ["add"]             = "Add",
            ["new"]             = "New",
            ["place"]           = "Place",
            ["error_prefix"]    = "Error: ",
            ["revit_ver"]       = "Revit 2025",

            // ── Settings window ───────────────────────────────────────────
            ["settings.title"]          = "Settings",
            ["settings.tab.appearance"] = "Appearance",
            ["settings.tab.language"]   = "Language",
            ["settings.tab.license"]    = "License",
            ["settings.tab.worksets"]   = "Worksets",
            ["settings.tab.heights"]    = "Heights",

            ["settings.appearance.theme"]       = "Theme",
            ["settings.appearance.dark"]        = "Dark Mode",
            ["settings.appearance.light"]       = "Light Mode",
            ["settings.appearance.theme_hint"]  = "Switch between dark and light mode for all ME-Tools windows simultaneously.",

            ["settings.language.title"]   = "Language / Sprache / Limbă",
            ["settings.language.label"]   = "Language:",
            ["settings.language.restart"] = "Language change takes effect after restarting Revit.",

            ["settings.license.title"]    = "License Status",
            ["settings.license.activate"] = "Activate",
            ["settings.license.remove"]   = "Remove Key",
            ["settings.license.need"]     = "Need a license?  Contact: ",
            ["settings.license.key"]      = "Activation Key",

            ["settings.worksets.title"]       = "Standard Worksets",
            ["settings.worksets.hint"]        = "Define which worksets are created in workshared projects.\nEdit the list and click Save. Changes take effect immediately.",
            ["settings.worksets.remove"]      = "Remove Selected",
            ["settings.worksets.save"]        = "Save List",
            ["settings.worksets.apply_title"] = "Apply to Current Project",
            ["settings.worksets.apply_hint"]  = "Creates all worksets from the list above in the active Revit project.\nExisting worksets are skipped automatically. Worksharing must be active.",
            ["settings.worksets.create_btn"]  = "Create Standard Worksets in Project",
            ["settings.worksets.project"]     = "Worksets in Current Project",
            ["settings.worksets.project_hint"]= "Read-only list of all user worksets currently defined in the open Revit project.",
            ["settings.worksets.empty"]       = "The workset list is empty. Add worksets first.",
            ["settings.worksets.saved"]       = "Worksets Saved",
            ["settings.worksets.no_project"]  = "No active Revit project found.",
            ["settings.worksets.done_title"]  = "Standard Worksets — Done",

            ["settings.heights.title"]    = "Default Mounting Heights",
            ["settings.heights.rescan"]   = "Rescan",
            ["settings.heights.save"]     = "Save Overrides",
            ["settings.heights.scanning"] = "Scanning families, please wait...",
            ["settings.heights.no_default"]= "No family default",
            ["settings.heights.family_default"] = "Family default: ",
            ["settings.heights.saved"]    = "Saved ",

            // ── Lamp Placer ───────────────────────────────────────────────
            ["lamp.title"]              = "Lamp Placer",
            ["lamp.lighting_family"]    = "Lighting Family",
            ["lamp.placement"]          = "Placement",
            ["lamp.place_on_face"]      = "Place on Face",
            ["lamp.place_on_wp"]        = "Place on Work Plane",
            ["lamp.distribution"]       = "Distribution Mode",
            ["lamp.area_based"]         = "Area-based",
            ["lamp.manual_grid"]        = "Manual Grid",
            ["lamp.line"]               = "Line",
            ["lamp.sqm_per_lamp"]       = "m² per lamp:",
            ["lamp.room_presets"]       = "Room Presets",
            ["lamp.preset_name"]        = "Preset name (room type):",
            ["lamp.families"]           = "Families (family / type / count):",
            ["lamp.add_family"]         = "+ Add family",
            ["lamp.save_preset"]        = "Save preset",
            ["lamp.update_room"]        = "Update room",
            ["lamp.new_preset"]         = "New",
            ["lamp.by_spacing"]         = "By spacing",
            ["lamp.by_count"]           = "By count",
            ["lamp.count"]              = "Count:",
            ["lamp.lamp_orientation"]   = "Lamp orientation:",
            ["lamp.along_line"]         = "↔ Along line",
            ["lamp.perpendicular"]      = "⟂ Perpendicular",
            ["lamp.dimensions"]         = "Dimensions",
            ["lamp.reference_level"]    = "Reference Level",
            ["lamp.place_in_room"]      = "Place in Room",
            ["lamp.multiple_rooms"]     = "Multiple Rooms",
            ["lamp.place_along_line"]   = "Place Along Line",
            ["lamp.place_grid"]         = "Place Grid",
            ["lamp.rows"]               = "Rows:",
            ["lamp.cols"]               = "×  Cols:",
            ["lamp.lamp_spacing"]       = "Lamp spacing",
            ["lamp.select_family"]      = "Please select a family and type first.",
            ["lamp.select_at_least"]    = "Select at least one family.",
            ["lamp.waiting_guideline"]  = "... Waiting for guide line selection",
            ["lamp.dim_custom_hint"]    = "After placing, pick pairs of reference points to draw dimensions manually",
            ["lamp.deleted_preset"]     = "Deleted preset: ",
            ["lamp.saved_preset"]       = "Saved preset: ",
            ["lamp.no_levels"]          = "-- No levels found --",
            ["lamp.choose_preset"]      = "Choose room preset",
            ["lamp.new_preset_dbl"]     = "-- New preset --",

            // ── Fix Level ─────────────────────────────────────────────────
            ["fixlevel.title"]          = "Fix Level",
            ["fixlevel.heading"]        = "Assign schedule levels",
            ["fixlevel.description"]    = "Sockets and switches go to the storey's FFB level; ceiling lamps go to its UKD level. Targets are based on the active floor plan when you click Fix.",
            ["fixlevel.notice"]         = "⚠  Note: this tool physically moves elements to the correct Z height so the 3D model looks right, and updates the CAx level parameters (CAx_Trassenbezugsebene / CAx_Ebenenhohenwert) which your CAx schedules read from.\n\nIt does NOT change the 'Schedule Level' or 'Work Plane' shown in Revit's Properties panel — those are locked by Revit after placement and cannot be changed by any API or tool without deleting and recreating the element.",
            ["fixlevel.categories"]     = "Categories to fix",
            ["fixlevel.sockets"]        = "Sockets  (Electrical Fixtures -> FFB)",
            ["fixlevel.switches"]       = "Switches  (Lighting Devices -> FFB)",
            ["fixlevel.lamps"]          = "Lamps  (Lighting Fixtures -> ceiling/UKD)",
            ["fixlevel.skip_wall"]      = "Skip wall-mounted lamps (offset from host or wall-type name)",
            ["fixlevel.scope"]          = "Scope",
            ["fixlevel.active_view"]    = "Only what's visible in the active view",
            ["fixlevel.current_storey"] = "Everything on the current storey",
            ["fixlevel.whole_model"]    = "Whole model",
            ["fixlevel.preview_tip"]    = "Count how many elements would be moved without making any changes",
            ["fixlevel.preview_btn"]    = "Preview",
            ["fixlevel.fix_btn"]        = "Fix Levels",
            ["fixlevel.fixing"]         = "Fixing levels...",
            ["fixlevel.select_one"]     = "Select at least one category.",

            // ── Family Browser ────────────────────────────────────────────
            ["browser.title"]           = "Family Browser",
            ["browser.subtitle"]        = "Loaded _E_CAx families — grouped by category",
            ["browser.search"]          = "Search families...",
            ["browser.all"]             = "All",
            ["browser.load_from_disk"]  = "+ Load Family from Disk",
            ["browser.no_families"]     = "No families found.",
            ["browser.no_document"]     = "No document open.",
            ["browser.families_loaded"] = "families loaded",
            ["browser.select_rfa"]      = "Select Revit Family to Load",
            ["browser.type"]            = "type",
            ["browser.types"]           = "types",
            ["browser.families"]        = "families",
            ["browser.place_tip"]       = "Click to enter placement mode for this family",
            ["browser.place_btn"]       = "Place",

            // ── Statistics ────────────────────────────────────────────────
            ["stats.title"]         = "Statistics",
            ["stats.subtitle"]      = "Project element counts",
            ["stats.refresh"]       = "Refresh",
            ["stats.export"]        = "Export CSV",
            ["stats.refreshing"]    = "Refreshing...",
            ["stats.per_floor"]     = "Per floor",
            ["stats.sockets_type"]  = "Sockets by type",
            ["stats.switches_type"] = "Switches by type",
            ["stats.electrical"]    = "Electrical",

            // ── Family Placer ─────────────────────────────────────────────
            ["placer.title"]        = "Family Placer",
            ["placer.template"]     = "Template",
            ["placer.arrangement"]  = "Arrangement",
            ["placer.stacked"]      = "↕  Stacked",
            ["placer.side_by_side"] = "↔  Side by Side",
            ["placer.level"]        = "Level",
            ["placer.famille"]      = "Family",
            ["placer.niveau"]       = "Niveau",
            ["placer.off_x"]        = "Off X",
            ["placer.off_y"]        = "Off Y",
            ["placer.add_slot"]     = "+ Add Slot",
            ["placer.place"]        = "▶  Place",
            ["placer.multi_place"]  = "⊕  Multi-Place",
            ["placer.save_tpl"]     = "Save",
            ["placer.loading"]      = "Loading...",
            ["placer.no_selection"] = "-- No Selection --",
            ["placer.select_tpl"]   = "— Select Template —",
            ["placer.select_family"]= "Select a family first.",
            ["placer.0_configured"] = "0 families configured",
            ["lamp.select_family_dropdown"] = "-- Select Family --",
            ["lamp.detect_hosting"]     = "Select a family to detect hosting.",
            ["lamp.face_available"]     = " - face placement available.",
            ["lamp.wp_only"]            = " - work plane / level only.",
            ["lamp.fallback_hint"]      = "Used as a reliable fallback when no slab face is found at the UKD.",
            ["lamp.area_info"]          = "Lamps distributed symmetrically from room center · Room boundaries checked · Height = room UKD",
            ["lamp.auto_grid"]          = "→ auto grid based on room area ÷ {0} m²/lamp",
            ["lamp.help_area"]          = "Area-based: click \"Place in Room\" and pick one room. If presets are saved, you will be asked which to apply: each entry's lamps are spread evenly across the room and the room is renamed to the preset. Choose \"No preset\" to place the selected family only. Use \"Multiple Rooms\" to place the selected family in several rooms at once (no preset).",
            ["lamp.help_grid"]          = "Manual Grid: click the 4 corners of the area in order. Rows × Cols lamps are placed evenly inside.",
            ["lamp.help_line"]          = "Line: 1) Draw a detail line in Revit.  2) Click \"Place Along Line\" and select the line(s), then click the green check (Finish) at the top.  The lamps are spread evenly along it.",
            ["lamp.families_count"]     = "families",
            ["lamp.no_preset"]          = "No preset",

            // ── Family Placer (full) ──────────────────────────────────────
            ["placer.off_x"]            = "Off X",
            ["placer.off_y"]            = "Off Y",
            ["placer.help"]             = "Place: position the family (SPACEBAR rotates, click a wall face to host) and click once - it finishes after that one drop. Multi-Place: same, but click several positions and press ESC to finish. Wall detection and free work plane are supported.",
            ["placer.families_configured"] = "families configured",
            ["placer.family_params"]    = "Family Parameters",
            ["placer.no_params"]        = "No editable instance parameters.",
            ["placer.tpl_name"]         = "Template name:",

            // ── Statistics categories ─────────────────────────────────────
            ["stats.sockets"]           = "Sockets",
            ["stats.switches"]          = "Switches",
            ["stats.lamps"]             = "Lamps",
            ["stats.cat.lamps"]         = "Lamps (Lighting Fixtures)",
            ["stats.cat.sockets"]       = "Sockets (Electrical Fixtures)",
            ["stats.cat.switches"]      = "Switches (Lighting Devices)",
            ["stats.cat.panels"]        = "Electrical Equipment / Panels",
            ["stats.cat.fire"]          = "Fire Alarm Devices",
            ["stats.cat.data"]          = "Data Devices",
            ["stats.cat.comms"]         = "Communication Devices",
            ["stats.cable"]             = "Cable & Containment",
            ["stats.mech"]              = "Mechanical & Plumbing",
            ["stats.spaces"]            = "Spaces & Levels",

            // ── Family Browser groups ─────────────────────────────────────
            ["browser.grp.sockets"]     = "Sockets",
            ["browser.grp.switches"]    = "Switches",
            ["browser.grp.lighting"]    = "Lighting",
            ["browser.grp.panels"]      = "Panels",
            ["browser.grp.fire"]        = "Fire Alarm",
            ["browser.grp.data"]        = "Data / Comms",
            ["browser.grp.sensors"]     = "Sensors",
            ["browser.grp.other"]       = "Other",
            ["browser.grp.lightning"]   = "Lightning Protection",
            ["browser.grp.conduit"]     = "Conduit & Fittings",

            // ── Settings appearance (full) ────────────────────────────────
            ["settings.appearance.theme_label"] = "Theme",
        };

        // ── German translations ───────────────────────────────────────────
        private static readonly Dictionary<string, string> _de = new()
        {
            ["cancel"]          = "Abbrechen",
            ["save"]            = "Speichern",
            ["delete"]          = "Löschen",
            ["close"]           = "Schließen",
            ["refresh"]         = "Aktualisieren",
            ["none"]            = "Keine",
            ["auto"]            = "Auto",
            ["custom"]          = "Benutzerdefiniert",
            ["preview"]         = "Vorschau",
            ["add"]             = "Hinzufügen",
            ["new"]             = "Neu",
            ["place"]           = "Platzieren",
            ["error_prefix"]    = "Fehler: ",
            ["revit_ver"]       = "Revit 2025",

            ["settings.title"]          = "Einstellungen",
            ["settings.tab.appearance"] = "Darstellung",
            ["settings.tab.language"]   = "Sprache",
            ["settings.tab.license"]    = "Lizenz",
            ["settings.tab.worksets"]   = "Worksets",
            ["settings.tab.heights"]    = "Höhen",

            ["settings.appearance.theme"]       = "Design",
            ["settings.appearance.dark"]        = "Dunkelmodus",
            ["settings.appearance.light"]       = "Hellmodus",
            ["settings.appearance.theme_hint"]  = "Wechseln Sie zwischen dunklem und hellem Modus für alle ME-Tools-Fenster.",

            ["settings.language.title"]   = "Sprache / Language / Limbă",
            ["settings.language.label"]   = "Sprache:",
            ["settings.language.restart"] = "Sprachänderung wird nach dem Neustart von Revit wirksam.",

            ["settings.license.title"]    = "Lizenzstatus",
            ["settings.license.activate"] = "Aktivieren",
            ["settings.license.remove"]   = "Schlüssel entfernen",
            ["settings.license.need"]     = "Lizenz benötigt? Kontakt: ",
            ["settings.license.key"]      = "Aktivierungsschlüssel",

            ["settings.worksets.title"]       = "Standard-Worksets",
            ["settings.worksets.hint"]        = "Definieren Sie, welche Worksets in geteilten Projekten erstellt werden.\nListe bearbeiten und Speichern klicken.",
            ["settings.worksets.remove"]      = "Ausgewählte entfernen",
            ["settings.worksets.save"]        = "Liste speichern",
            ["settings.worksets.apply_title"] = "Im aktuellen Projekt anwenden",
            ["settings.worksets.apply_hint"]  = "Erstellt alle Worksets der obigen Liste im aktiven Revit-Projekt.\nBestehende Worksets werden automatisch übersprungen.",
            ["settings.worksets.create_btn"]  = "Standard-Worksets im Projekt erstellen",
            ["settings.worksets.project"]     = "Worksets im aktuellen Projekt",
            ["settings.worksets.project_hint"]= "Schreibgeschützte Liste aller Benutzer-Worksets im geöffneten Projekt.",
            ["settings.worksets.empty"]       = "Die Workset-Liste ist leer. Zuerst Worksets hinzufügen.",
            ["settings.worksets.saved"]       = "Worksets gespeichert",
            ["settings.worksets.no_project"]  = "Kein aktives Revit-Projekt gefunden.",
            ["settings.worksets.done_title"]  = "Standard-Worksets — Fertig",

            ["settings.heights.title"]    = "Standard-Montagehöhen",
            ["settings.heights.rescan"]   = "Neu scannen",
            ["settings.heights.save"]     = "Überschreibungen speichern",
            ["settings.heights.scanning"] = "Familien werden gescannt, bitte warten...",
            ["settings.heights.no_default"]= "Kein Familienstandard",
            ["settings.heights.family_default"] = "Familienstandard: ",
            ["settings.heights.saved"]    = "Gespeichert ",

            ["lamp.title"]              = "Leuchtenplanung",
            ["lamp.lighting_family"]    = "Leuchtenfamilie",
            ["lamp.placement"]          = "Platzierung",
            ["lamp.place_on_face"]      = "Auf Fläche platzieren",
            ["lamp.place_on_wp"]        = "Auf Arbeitsebene platzieren",
            ["lamp.distribution"]       = "Verteilungsmodus",
            ["lamp.area_based"]         = "Flächenbasiert",
            ["lamp.manual_grid"]        = "Manuellem Raster",
            ["lamp.line"]               = "Linie",
            ["lamp.sqm_per_lamp"]       = "m² pro Leuchte:",
            ["lamp.room_presets"]       = "Raum-Voreinstellungen",
            ["lamp.preset_name"]        = "Voreinstellungsname (Raumtyp):",
            ["lamp.families"]           = "Familien (Familie / Typ / Anzahl):",
            ["lamp.add_family"]         = "+ Familie hinzufügen",
            ["lamp.save_preset"]        = "Voreinstellung speichern",
            ["lamp.update_room"]        = "Raum aktualisieren",
            ["lamp.new_preset"]         = "Neu",
            ["lamp.by_spacing"]         = "Nach Abstand",
            ["lamp.by_count"]           = "Nach Anzahl",
            ["lamp.count"]              = "Anzahl:",
            ["lamp.lamp_orientation"]   = "Leuchtenausrichtung:",
            ["lamp.along_line"]         = "↔ Entlang der Linie",
            ["lamp.perpendicular"]      = "⟂ Senkrecht",
            ["lamp.dimensions"]         = "Bemaßungen",
            ["lamp.reference_level"]    = "Referenzebene",
            ["lamp.place_in_room"]      = "Im Raum platzieren",
            ["lamp.multiple_rooms"]     = "Mehrere Räume",
            ["lamp.place_along_line"]   = "Entlang Linie platzieren",
            ["lamp.place_grid"]         = "Raster platzieren",
            ["lamp.rows"]               = "Zeilen:",
            ["lamp.cols"]               = "× Spalten:",
            ["lamp.lamp_spacing"]       = "Leuchtenabstand",
            ["lamp.select_family"]      = "Bitte zuerst Familie und Typ auswählen.",
            ["lamp.waiting_guideline"]  = "... Wartet auf Führungslinienauswahl",
            ["lamp.dim_custom_hint"]    = "Nach dem Platzieren Referenzpunktpaare wählen, um Bemaßungen zu zeichnen",
            ["lamp.deleted_preset"]     = "Voreinstellung gelöscht: ",
            ["lamp.saved_preset"]       = "Voreinstellung gespeichert: ",
            ["lamp.no_levels"]          = "-- Keine Ebenen gefunden --",
            ["lamp.choose_preset"]      = "Raum-Voreinstellung wählen",
            ["lamp.new_preset_dbl"]     = "-- Neue Voreinstellung --",

            ["fixlevel.title"]          = "Ebene korrigieren",
            ["fixlevel.heading"]        = "Terminierungsebenen zuweisen",
            ["fixlevel.description"]    = "Steckdosen und Schalter gehen zur FFB-Ebene; Deckenleuchen zur UKD-Ebene.",
            ["fixlevel.notice"]         = "⚠  Hinweis: Dieses Tool verschiebt Elemente physisch auf die korrekte Z-Höhe und aktualisiert die CAx-Parameter. Die 'Terminierungsebene' und 'Arbeitsebene' in den Revit-Eigenschaften können nicht geändert werden.",
            ["fixlevel.categories"]     = "Zu korrigierende Kategorien",
            ["fixlevel.sockets"]        = "Steckdosen  (Elektrische Einbauten -> FFB)",
            ["fixlevel.switches"]       = "Schalter  (Beleuchtungssteuerung -> FFB)",
            ["fixlevel.lamps"]          = "Leuchten  (Beleuchtung -> Decke/UKD)",
            ["fixlevel.skip_wall"]      = "Wandleuchten überspringen",
            ["fixlevel.scope"]          = "Umfang",
            ["fixlevel.active_view"]    = "Nur in aktiver Ansicht sichtbare Elemente",
            ["fixlevel.current_storey"] = "Alles im aktuellen Geschoss",
            ["fixlevel.whole_model"]    = "Gesamtes Modell",
            ["fixlevel.preview_tip"]    = "Anzahl der zu verschiebenden Elemente zählen, ohne Änderungen vorzunehmen",
            ["fixlevel.preview_btn"]    = "Vorschau",
            ["fixlevel.fix_btn"]        = "Ebenen korrigieren",
            ["fixlevel.fixing"]         = "Ebenen werden korrigiert...",
            ["fixlevel.select_one"]     = "Mindestens eine Kategorie auswählen.",

            ["browser.title"]           = "Familien-Browser",
            ["browser.subtitle"]        = "Geladene _E_CAx-Familien — nach Kategorie gruppiert",
            ["browser.search"]          = "Familien suchen...",
            ["browser.all"]             = "Alle",
            ["browser.load_from_disk"]  = "+ Familie von Festplatte laden",
            ["browser.no_families"]     = "Keine Familien gefunden.",
            ["browser.no_document"]     = "Kein Dokument geöffnet.",
            ["browser.families_loaded"] = "Familien geladen",
            ["browser.select_rfa"]      = "Revit-Familie zum Laden auswählen",
            ["browser.place_btn"]       = "Platzieren",

            ["stats.title"]         = "Statistiken",
            ["stats.subtitle"]      = "Projektelement-Zählungen",
            ["stats.refresh"]       = "Aktualisieren",
            ["stats.export"]        = "CSV exportieren",
            ["stats.refreshing"]    = "Wird aktualisiert...",
            ["stats.per_floor"]     = "Pro Geschoss",
            ["stats.sockets_type"]  = "Steckdosen nach Typ",
            ["stats.switches_type"] = "Schalter nach Typ",
            ["stats.electrical"]    = "Elektro",

            ["placer.title"]        = "Familienplanung",
            ["placer.template"]     = "Vorlage",
            ["placer.arrangement"]  = "Anordnung",
            ["placer.stacked"]      = "↕  Übereinander",
            ["placer.side_by_side"] = "↔  Nebeneinander",
            ["placer.level"]        = "Ebene",
            ["placer.famille"]      = "Familie",
            ["placer.add_slot"]     = "+ Slot hinzufügen",
            ["placer.place"]        = "▶  Platzieren",
            ["placer.multi_place"]  = "⊕  Mehrfach platzieren",
            ["placer.save_tpl"]     = "Speichern",
            ["placer.loading"]      = "Lädt...",
            ["placer.no_selection"] = "-- Keine Auswahl --",
            ["placer.select_tpl"]   = "— Vorlage wählen —",
            ["placer.select_family"]= "Zuerst eine Familie auswählen.",
            ["placer.0_configured"] = "0 Familien konfiguriert",
            ["lamp.select_family_dropdown"] = "-- Familie auswählen --",
            ["lamp.detect_hosting"]     = "Familie auswählen, um Hosting zu erkennen.",
            ["lamp.face_available"]     = " - Flächenplatzierung verfügbar.",
            ["lamp.wp_only"]            = " - nur Arbeitsebene / Ebene.",
            ["lamp.fallback_hint"]      = "Wird als zuverlässiger Fallback verwendet, wenn keine Deckenfläche am UKD gefunden wird.",
            ["lamp.area_info"]          = "Leuchten symmetrisch ab Raummitte verteilt · Raumgrenzen geprüft · Höhe = Raum-UKD",
            ["lamp.auto_grid"]          = "→ automatisches Raster nach Raumfläche ÷ {0} m²/Leuchte",
            ["lamp.help_area"]          = "Flächenbasiert: \"Im Raum platzieren\" klicken und einen Raum wählen. Wenn Voreinstellungen gespeichert sind, werden Sie gefragt, welche angewendet werden soll. \"Mehrere Räume\" platziert die gewählte Familie in mehreren Räumen gleichzeitig.",
            ["lamp.help_grid"]          = "Manuelles Raster: die 4 Ecken der Fläche der Reihe nach anklicken. Zeilen × Spalten Leuchten werden gleichmäßig platziert.",
            ["lamp.help_line"]          = "Linie: 1) Detaillinie in Revit zeichnen. 2) \"Entlang Linie platzieren\" klicken und die Linie(n) wählen, dann oben den grünen Haken (Fertig) klicken.",
            ["lamp.families_count"]     = "Familien",
            ["lamp.no_preset"]          = "Keine Voreinstellung",

            ["placer.off_x"]            = "Vers X",
            ["placer.off_y"]            = "Vers Y",
            ["placer.help"]             = "Platzieren: Familie positionieren (LEERTASTE dreht, Wandfläche anklicken zum Hosten) und einmal klicken. Mehrfach platzieren: mehrere Positionen klicken und ESC zum Beenden.",
            ["placer.families_configured"] = "Familien konfiguriert",
            ["placer.family_params"]    = "Familienparameter",
            ["placer.no_params"]        = "Keine bearbeitbaren Instanzparameter.",
            ["placer.tpl_name"]         = "Vorlagenname:",

            ["stats.sockets"]           = "Steckdosen",
            ["stats.switches"]          = "Schalter",
            ["stats.lamps"]             = "Leuchten",
            ["stats.cat.lamps"]         = "Leuchten (Beleuchtung)",
            ["stats.cat.sockets"]       = "Steckdosen (Elektr. Einbauten)",
            ["stats.cat.switches"]      = "Schalter (Beleuchtungssteuerung)",
            ["stats.cat.panels"]        = "Elektr. Betriebsmittel / Verteiler",
            ["stats.cat.fire"]          = "Brandmeldegeräte",
            ["stats.cat.data"]          = "Datengeräte",
            ["stats.cat.comms"]         = "Kommunikationsgeräte",
            ["stats.cable"]             = "Kabel & Trassen",
            ["stats.mech"]              = "Mechanik & Sanitär",
            ["stats.spaces"]            = "Räume & Ebenen",

            ["browser.grp.sockets"]     = "Steckdosen",
            ["browser.grp.switches"]    = "Schalter",
            ["browser.grp.lighting"]    = "Beleuchtung",
            ["browser.grp.panels"]      = "Verteiler",
            ["browser.grp.fire"]        = "Brandmeldung",
            ["browser.grp.data"]        = "Daten / Komm.",
            ["browser.grp.sensors"]     = "Sensoren",
            ["browser.grp.other"]       = "Sonstige",
            ["browser.grp.lightning"]   = "Blitzschutz",
            ["browser.grp.conduit"]     = "Rohrformstuecke",

            ["settings.appearance.theme_label"] = "Design",
        };

        // ── Romanian translations ─────────────────────────────────────────
        private static readonly Dictionary<string, string> _ro = new()
        {
            ["cancel"]          = "Anulare",
            ["save"]            = "Salvare",
            ["delete"]          = "Stergere",
            ["close"]           = "Inchide",
            ["refresh"]         = "Reimprospatare",
            ["none"]            = "Niciunul",
            ["auto"]            = "Auto",
            ["custom"]          = "Personalizat",
            ["preview"]         = "Previzualizare",
            ["add"]             = "Adaugare",
            ["new"]             = "Nou",
            ["place"]           = "Plasare",
            ["error_prefix"]    = "Eroare: ",
            ["revit_ver"]       = "Revit 2025",

            ["settings.title"]          = "Setari",
            ["settings.tab.appearance"] = "Aspect",
            ["settings.tab.language"]   = "Limba",
            ["settings.tab.license"]    = "Licenta",
            ["settings.tab.worksets"]   = "Worksets",
            ["settings.tab.heights"]    = "Inaltimi",

            ["settings.appearance.theme"]       = "Tema",
            ["settings.appearance.dark"]        = "Mod intunecat",
            ["settings.appearance.light"]       = "Mod luminos",
            ["settings.appearance.theme_hint"]  = "Comutati intre modul intunecat si luminos pentru toate ferestrele ME-Tools.",

            ["settings.language.title"]   = "Limba / Sprache / Language",
            ["settings.language.label"]   = "Limba:",
            ["settings.language.restart"] = "Schimbarea limbii se aplica dupa repornirea Revit.",

            ["settings.license.title"]    = "Status Licenta",
            ["settings.license.activate"] = "Activare",
            ["settings.license.remove"]   = "Eliminare cheie",
            ["settings.license.need"]     = "Aveti nevoie de o licenta? Contact: ",
            ["settings.license.key"]      = "Cheie de activare",

            ["settings.worksets.title"]       = "Worksets standard",
            ["settings.worksets.hint"]        = "Definiti ce worksets sunt create in proiectele partajate.\nEditati lista si apasati Salvare.",
            ["settings.worksets.remove"]      = "Eliminare selectat",
            ["settings.worksets.save"]        = "Salvare lista",
            ["settings.worksets.apply_title"] = "Aplicare in proiectul curent",
            ["settings.worksets.apply_hint"]  = "Creeaza toate worksets din lista de mai sus in proiectul Revit activ.\nWorksets existente sunt sarite automat.",
            ["settings.worksets.create_btn"]  = "Creare worksets standard in proiect",
            ["settings.worksets.project"]     = "Worksets in proiectul curent",
            ["settings.worksets.project_hint"]= "Lista doar pentru citire a tuturor worksets utilizator definite in proiectul deschis.",
            ["settings.worksets.empty"]       = "Lista de worksets este goala. Adaugati mai intai worksets.",
            ["settings.worksets.saved"]       = "Worksets salvate",
            ["settings.worksets.no_project"]  = "Nu s-a gasit niciun proiect Revit activ.",
            ["settings.worksets.done_title"]  = "Worksets standard — Finalizat",

            ["settings.heights.title"]    = "Inaltimi de montaj implicite",
            ["settings.heights.rescan"]   = "Rescanare",
            ["settings.heights.save"]     = "Salvare modificari",
            ["settings.heights.scanning"] = "Scanare familii, asteptati...",
            ["settings.heights.no_default"]= "Nicio valoare implicita",
            ["settings.heights.family_default"] = "Valoare implicita familie: ",
            ["settings.heights.saved"]    = "Salvat ",

            ["lamp.title"]              = "Plasare Corpuri",
            ["lamp.lighting_family"]    = "Familie Iluminat",
            ["lamp.placement"]          = "Plasare",
            ["lamp.place_on_face"]      = "Plasare pe fata",
            ["lamp.place_on_wp"]        = "Plasare pe plan de lucru",
            ["lamp.distribution"]       = "Mod distributie",
            ["lamp.area_based"]         = "Bazat pe arie",
            ["lamp.manual_grid"]        = "Grila manuala",
            ["lamp.line"]               = "Linie",
            ["lamp.sqm_per_lamp"]       = "m² per corp:",
            ["lamp.room_presets"]       = "Presetari camera",
            ["lamp.preset_name"]        = "Nume presetare (tip camera):",
            ["lamp.families"]           = "Familii (familie / tip / numar):",
            ["lamp.add_family"]         = "+ Adauga familie",
            ["lamp.save_preset"]        = "Salvare presetare",
            ["lamp.update_room"]        = "Actualizare camera",
            ["lamp.new_preset"]         = "Nou",
            ["lamp.by_spacing"]         = "Dupa distanta",
            ["lamp.by_count"]           = "Dupa numar",
            ["lamp.count"]              = "Numar:",
            ["lamp.lamp_orientation"]   = "Orientare corp:",
            ["lamp.along_line"]         = "↔ De-a lungul liniei",
            ["lamp.perpendicular"]      = "⟂ Perpendicular",
            ["lamp.dimensions"]         = "Cote",
            ["lamp.reference_level"]    = "Nivel referinta",
            ["lamp.place_in_room"]      = "Plasare in camera",
            ["lamp.multiple_rooms"]     = "Camere multiple",
            ["lamp.place_along_line"]   = "Plasare de-a lungul liniei",
            ["lamp.place_grid"]         = "Plasare grila",
            ["lamp.rows"]               = "Randuri:",
            ["lamp.cols"]               = "× Coloane:",
            ["lamp.lamp_spacing"]       = "Distanta corpuri",
            ["lamp.select_family"]      = "Va rugam selectati mai intai o familie si un tip.",
            ["lamp.waiting_guideline"]  = "... Asteptare selectie linie ghid",
            ["lamp.dim_custom_hint"]    = "Dupa plasare, selectati perechi de puncte de referinta pentru a desena cote",
            ["lamp.deleted_preset"]     = "Presetare stearsa: ",
            ["lamp.saved_preset"]       = "Presetare salvata: ",
            ["lamp.no_levels"]          = "-- Nu s-au gasit niveluri --",
            ["lamp.choose_preset"]      = "Alegeti presetarea camerei",
            ["lamp.new_preset_dbl"]     = "-- Presetare noua --",

            ["fixlevel.title"]          = "Corectare nivel",
            ["fixlevel.heading"]        = "Atribuire niveluri programare",
            ["fixlevel.description"]    = "Prizele si intrerupatoarele merg la nivelul FFB; corpurile de iluminat la nivelul UKD.",
            ["fixlevel.notice"]         = "⚠  Nota: Acest instrument muta fizic elementele la inaltimea Z corecta si actualizeaza parametrii CAx. 'Nivelul de programare' si 'Planul de lucru' din proprietatile Revit nu pot fi modificate.",
            ["fixlevel.categories"]     = "Categorii de corectat",
            ["fixlevel.sockets"]        = "Prize  (Instalatii electrice -> FFB)",
            ["fixlevel.switches"]       = "Intrerupatoare  (Dispozitive iluminat -> FFB)",
            ["fixlevel.lamps"]          = "Corpuri  (Corpuri de iluminat -> plafon/UKD)",
            ["fixlevel.skip_wall"]      = "Sariti corpurile montate pe perete",
            ["fixlevel.scope"]          = "Domeniu",
            ["fixlevel.active_view"]    = "Doar ce e vizibil in vederea activa",
            ["fixlevel.current_storey"] = "Tot ce e pe etajul curent",
            ["fixlevel.whole_model"]    = "Intregul model",
            ["fixlevel.preview_tip"]    = "Numara elementele care ar fi mutate fara a face modificari",
            ["fixlevel.preview_btn"]    = "Previzualizare",
            ["fixlevel.fix_btn"]        = "Corectare niveluri",
            ["fixlevel.fixing"]         = "Se corecteaza nivelurile...",
            ["fixlevel.select_one"]     = "Selectati cel putin o categorie.",

            ["browser.title"]           = "Browser Familii",
            ["browser.subtitle"]        = "Familii _E_CAx incarcate — grupate pe categorie",
            ["browser.search"]          = "Cautare familii...",
            ["browser.all"]             = "Toate",
            ["browser.load_from_disk"]  = "+ Incarcare familie de pe disc",
            ["browser.no_families"]     = "Nu s-au gasit familii.",
            ["browser.no_document"]     = "Niciun document deschis.",
            ["browser.families_loaded"] = "familii incarcate",
            ["browser.select_rfa"]      = "Selectati familia Revit de incarcat",
            ["browser.place_btn"]       = "Plasare",

            ["stats.title"]         = "Statistici",
            ["stats.subtitle"]      = "Numaratori elemente proiect",
            ["stats.refresh"]       = "Reimprospatare",
            ["stats.export"]        = "Export CSV",
            ["stats.refreshing"]    = "Se reimprospatare...",
            ["stats.per_floor"]     = "Pe etaj",
            ["stats.sockets_type"]  = "Prize dupa tip",
            ["stats.switches_type"] = "Intrerupatoare dupa tip",
            ["stats.electrical"]    = "Electric",

            ["placer.title"]        = "Plasare Familii",
            ["placer.template"]     = "Sablon",
            ["placer.arrangement"]  = "Aranjament",
            ["placer.stacked"]      = "↕  Suprapus",
            ["placer.side_by_side"] = "↔  Alaturate",
            ["placer.level"]        = "Nivel",
            ["placer.famille"]      = "Familie",
            ["placer.add_slot"]     = "+ Adauga slot",
            ["placer.place"]        = "▶  Plasare",
            ["placer.multi_place"]  = "⊕  Plasare multipla",
            ["placer.save_tpl"]     = "Salvare",
            ["placer.loading"]      = "Se incarca...",
            ["placer.no_selection"] = "-- Nicio selectie --",
            ["placer.select_tpl"]   = "— Selectati sablonul —",
            ["placer.select_family"]= "Selectati mai intai o familie.",
            ["placer.0_configured"] = "0 familii configurate",
            ["lamp.select_family_dropdown"] = "-- Selectati familia --",
            ["lamp.detect_hosting"]     = "Selectati o familie pentru a detecta gazduirea.",
            ["lamp.face_available"]     = " - plasare pe fata disponibila.",
            ["lamp.wp_only"]            = " - doar plan de lucru / nivel.",
            ["lamp.fallback_hint"]      = "Folosit ca rezerva fiabila cand nu se gaseste nicio fata de placa la UKD.",
            ["lamp.area_info"]          = "Corpuri distribuite simetric din centrul camerei · Limite camera verificate · Inaltime = UKD camera",
            ["lamp.auto_grid"]          = "→ grila automata pe baza ariei camerei ÷ {0} m²/corp",
            ["lamp.help_area"]          = "Bazat pe arie: apasati \"Plasare in camera\" si alegeti o camera. Daca presetarile sunt salvate, veti fi intrebat care sa fie aplicata. \"Camere multiple\" plaseaza familia selectata in mai multe camere simultan.",
            ["lamp.help_grid"]          = "Grila manuala: apasati cele 4 colturi ale zonei in ordine. Randuri × Coloane corpuri sunt plasate uniform.",
            ["lamp.help_line"]          = "Linie: 1) Desenati o linie de detaliu in Revit. 2) Apasati \"Plasare de-a lungul liniei\" si selectati linia(liniile), apoi apasati bifa verde (Finalizare) sus.",
            ["lamp.families_count"]     = "familii",
            ["lamp.no_preset"]          = "Fara presetare",

            ["placer.off_x"]            = "Dec X",
            ["placer.off_y"]            = "Dec Y",
            ["placer.help"]             = "Plasare: pozitionati familia (SPATIU roteste, click pe o fata de perete pentru gazduire) si apasati o data. Plasare multipla: la fel, dar apasati mai multe pozitii si ESC pentru finalizare.",
            ["placer.families_configured"] = "familii configurate",
            ["placer.family_params"]    = "Parametri familie",
            ["placer.no_params"]        = "Niciun parametru de instanta editabil.",
            ["placer.tpl_name"]         = "Nume sablon:",

            ["stats.sockets"]           = "Prize",
            ["stats.switches"]          = "Intrerupatoare",
            ["stats.lamps"]             = "Corpuri",
            ["stats.cat.lamps"]         = "Corpuri (Corpuri de iluminat)",
            ["stats.cat.sockets"]       = "Prize (Instalatii electrice)",
            ["stats.cat.switches"]      = "Intrerupatoare (Dispozitive iluminat)",
            ["stats.cat.panels"]        = "Echipamente electrice / Tablouri",
            ["stats.cat.fire"]          = "Dispozitive alarma incendiu",
            ["stats.cat.data"]          = "Dispozitive date",
            ["stats.cat.comms"]         = "Dispozitive comunicatii",
            ["stats.cable"]             = "Cabluri & Trasee",
            ["stats.mech"]              = "Mecanica & Sanitare",
            ["stats.spaces"]            = "Spatii & Niveluri",

            ["browser.grp.sockets"]     = "Prize",
            ["browser.grp.switches"]    = "Intrerupatoare",
            ["browser.grp.lighting"]    = "Iluminat",
            ["browser.grp.panels"]      = "Tablouri",
            ["browser.grp.fire"]        = "Alarma incendiu",
            ["browser.grp.data"]        = "Date / Comm.",
            ["browser.grp.sensors"]     = "Senzori",
            ["browser.grp.other"]       = "Altele",
            ["browser.grp.lightning"]   = "Protectie la trasnet",
            ["browser.grp.conduit"]     = "Fitinguri tub",

            ["settings.appearance.theme_label"] = "Tema",
        };
    }
}
